### ISSUE TITLE
Support generating an xcworkspace instead of separate xcodeprojs

### ISSUE THREAD

**Issue by mikehaney24** [square/cocoapods-generate#13]
If pod gen is given a list of podspecs, can an xcworkspace containing all the generated projects be generated? Perhaps an additional --gen-workspace argument can be added to implement this functionality. In this case, --auto-open would open the workspace, as opposed to opening all generated projects individually.

**Comment by segiddins** [comment]
Seems like a reasonable option to add!

**Comment by paulb777** [comment]
I've started work on a PR.

**Comment by paulb777** [comment]
OK to close this since #19 would likely be sufficient for most use cases. #19 still requires a primary development pod and only the primary pod's tests are included. However, development versions of all dependencies can now be included.  I'm not sure the complexity of implementing a full development environment, including tests, for all requested pods in the same workspace is justified.
